"""added communication settings to User

Revision ID: 47cc84392e91
Revises: 2d1c762acb14
Create Date: 2020-12-16 22:09:10.873458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47cc84392e91'
down_revision = '2d1c762acb14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('send_emails', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('send_texts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'send_texts')
    op.drop_column('users', 'send_emails')
    # ### end Alembic commands ###
