"""empty message

Revision ID: 8967890f23bb
Revises: 47cc84392e91
Create Date: 2020-12-19 10:41:53.978174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8967890f23bb'
down_revision = '47cc84392e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE users SET send_emails = 1;")
    op.execute("UPDATE users SET send_texts = 0;")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
